apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chproxyd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: chproxyd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://nexus.mamba.ru/repository/helm/roadrunner-microservice-6.0.10.tgz'
      chart: roadrunner-microservice
      targetRevision: 6.0.10
      helm:
        valueFiles:
          - $values/chproxyd/chproxyd-values.yaml
    - repoURL: 'https://github.com/PototskiyVI/k8s.git'
      targetRevision: main
      ref: values
