apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub-test-from-argo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: jupyterhub-test-from-argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: 'https://jupyterhub.github.io/helm-chart'
      chart: jupyterhub
      targetRevision: 4.1.0
      helm:
        valueFiles:
          - $values/helm/jupyter-values.yaml
    - repoURL: 'https://github.com/PototskiyVI/k8s.git'
      targetRevision: master
      ref: values