---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-notebook
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jovyan"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-notebook
  namespace: jupyterhub-test-from-argo
spec:
  storageClassName: ""
  volumeName: share-notebook
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi